




# Excel columns for the Vrbo listings
EXCEL_LISTING_COLUMNS = [
    "listingID",
    "title",
    "price",
    "link",
    "image_URL",
    "amenities",
    "bedCount",
    "bathCount",
    "guestCount",
    "location description",
    "attractions",
    "resturants",
    "location",
]

# Keywords that are relevant for attractions and resturants
attraction_resturant_keywords = {
    "beach",
    "cafe",
    "café",
    "sushi",
    "coffee",
    "grill",
    "bar",
    "park",
    "museum",
    "bakery",
    "aquarium",
    "market",
    "jardin",
    "square",
    "castle",
    "garden",
    "temple",
    "port",
}



# Categories of amenities that are relevant to users
# Vrbo centered amenities
relevant_amenities = {
    "High-Speed wifi": {
        "high-speed wifi",
        "fast internet",
        "broadband",
        "high speed internet",
    },
    "Wifi": {"wifi", "internet"},
    "Ocean view": {
        "ocean view",
        "scenic view",
        "sea view",
        "water view",
        "location type beach",
        "near the ocean",
        "near the sea",
    },
    "Waterfront Location": {"on the waterfront"},
    "City view": {
        "city view",
        "urban view",
        "skyline view",
        "downtown",
        "location type downtown",
        "downtown",
        "near the city center",
        "in the city center",
    },
    "Mountian View": {"in the mountains"},
    "Village Location": {"in a village"},
    "Patio": {"patio", "deck", "veranda", "porch"},
    "Outdoor space": {
        "outdoor space",
        "garden",
        "yard",
        "backyard",
        "courtyard",
        "balcony",
    },
    "Free parking": {
        "free parking",
        "parking",
        "on-site parking",
        "garage",
        "parking space",
    },
    "Dedicated workspace": {
        "dedicated workspace",
        "workspace",
        "office",
        "desk",
        "work area",
        "home office",
    },
    "Kitchen": {"kitchen", "full kitchen", "gourmet kitchen", "cooking area"},
    "Kitchenette": {"kitchenette", "small kitchen", "compact kitchen"},
    "Books": {"library", "books", "reading room", "study", "book collection"},
    "Secure Storage": {"secure storage", "vault", "safe", "lockbox", "security box"},
    "Fireplace": {"fireplace", "hearth"},
    "Pet friendly": {
        "pet friendly",
        "pet-friendly",
        "pets allowed",
        "pet accommodations",
    },
    "Fire extinguisher": {"fire extinguisher", "extinguisher"},
    "Carbon monoxide alarm": {
        "carbon monoxide alarm",
        "carbon monoxide detector",
        "co alarm",
        "co detector",
    },
    "Coffee": {
        "coffee",
        "coffee maker",
        "tea kettle",
        "coffee machine",
        "espresso machine",
        "coffee/tea maker",
    },
    "Smart TV": {"smart tv", "smart-tv"},
    "TV": {"tv", "flat-screen tv", "hdtv"},
    "Dining Room": {"dining", "dining area", "dining room", "dining space"},
    "Living Room": {"living", "living area", "living room", "lounge", "sitting area"},
    "Air Conditioning": {"air conditioning", "ac", "a/c", "cooling", "climate control"},
    "Heating": {"heating", "heater", "warmth", "heat"},
    "Open floor plan": {"open floor plan", "open concept", "open layout"},
    "Washing Machine": {"washing machine"},
    "Elevator": {"elevator"},
}



# Adjectives to best describe spaces to users
# Emphasis on adj's that have been entered more than once
# ex: lush, seaside, oasis
descriptive_categories = [
    "Rustic",
    "Waterfront",
    "Historic",
    "Scenic",
    "Countryside",
    "Vintage",
    "Industrial",
    "Cozy",
    "Tropical",
    "Secluded",
    "Artistic",
    "Spacious",
    "Sustainable",
    "Beachfront",
    "Villa",
    "Lush",
    "Minimalist",
    "Romantic",
    "Industrial",
    "Panoramic",
    "Riverfront",
    "Cultural",
    "Artistic",
    "Nightlife",
    "Oasis",
    "Oasis",
    "Walkable",
    "Trendy",
    "Downtown",
    "Mountainous",
    "Riverside",
    "Cottage-style",
    "Adventurous",
    "Vineyard",
    "Waterfront",
    "Outskirts",
    "Tranquil",
    "Architectural",
    "Innovative",
    "Cityscape",
]




# Currently, these categories are not being used
category_labels = [
    "Modern",
    "Rustic",
    "Waterfront",
    "Unique",
    "Luxury",
    "Historic",
    "Scenic",
    "Urban",
    "Countryside",
    "Vintage",
    "Industrial",
    "Cozy",
    "Tropical",
    "Elegant",
    "Secluded",
    "Artistic",
    "Spacious",
    "Sustainable",
    "Loft",
    "Villa",
    "Lush",
    "Contemporary",
    "Charming",
    "Minimalist",
    "Eco-Friendly",
    "Sophisticated",
    "Retro",
    "Bohemian",
    "Classic",
    "High-Tech",
    "Quaint",
    "Serene",
    "Mountain View",
    "Beachfront",
    "Seafront",
    "Nature Retreat",
    "Private",
    "Pet-Friendly",
    "Family-Friendly",
    "Romantic",
    "Green",
    "Industrial Chic",
    "Converted Warehouse",
    "Farmhouse",
    "Manor",
    "Palatial",
    "Penthouse",
    "Treehouse",
    "Cottage",
    "Cabin",
    "Bungalow",
    "Studio",
    "Mansion",
    "Desert",
    "Forest",
    "Lakefront",
    "Snowfront",
    "Ski-in/Ski-out",
    "Panoramic Views",
    "Balcony",
    "Terrace",
    "Courtyard",
    "Atrium",
    "Sunroom",
    "Solarium",
    "Veranda",
    "Gazebo",
    "Pergola",
    "Waterfall",
    "Pond",
    "Stream",
    "Riverfront",
    "Historical Landmark",
    "Cultural Hub",
    "Art District",
    "Shopping District",
    "Dining District",
    "Nightlife",
    "Business District",
    "Tech Hub",
    "Educational Hub",
    "Sports Complex",
    "Entertainment Center",
    "Wellness Retreat",
    "Golf Course",
    "Marina",
    "Dock",
    "Urban Oasis",
    "Beach Access",
    "Walkable",
    "Trendy",
    "Suburban",
    "College Town",
    "Downtown",
    "Historic Quarter",
    "Seaside",
    "Boutique",
    "Urban Escape",
    "Mountain Cabin",
    "Lake House",
    "Riverside",
    "Countryside Cottage",
    "Nature Reserve",
    "Beach House",
    "Adventure Retreat",
    "Cultural Center",
    "Festival Area",
    "Convention Center",
    "Transit-Friendly",
    "Cycling-Friendly",
    "Hiking Trails",
    "Vineyard",
    "Winery",
    "Orchard",
    "Farm Stay",
    "Historic District",
    "Urban Village",
    "Waterfront Condo",
    "City Center",
    "Outskirts",
    "Rustic Charm",
    "Modern Comfort",
    "Tranquil",
    "Eco-Retreat",
    "Heritage",
    "Architectural Gem",
    "Chic",
    "Design",
    "Innovative",
    "Efficient",
    "Rooftop",
    "Garden",
    "Urban Loft",
    "Hillside",
    "Suburban Oasis",
    "City Life",
    "Water Views",
    "Entertainment Hub",
    "Luxury Condo",
    "Sprawling Estate",
    "Riverside Retreat"
]